### ISSUE TITLE
改善点

### ISSUE THREAD

**Issue by 5m4r7** [EdamAme-x/JSPCE#1]
ロゴの統一、トラブル防止のため自身での作成
JSの使い方の確認
信憑性の向上など
シェアを伸ばすためには必須

**Comment by EdamAme-x** [comment]
## 現状
- [x] ロゴの統一
- [x] 著作権 (自作)
- [x] JSのリファクタ

**Comment by EdamAme-x** [comment]
タスク完了

**Comment by 5m4r7** [comment]
了解
ありがとうございました
